version: '3'

services:
    mongodb:
        image: mongo:3.0.15
        container_name: norse_mongodb_prod
        ports:
            - "5002:27017"
        volumes:
            - "./docker/shared/.data/mongodb:/data/db"

    app:
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        container_name: norse_app_prod
        ports:
            - "8082:80"
        volumes:
            - "./docker/nginx/prod/sites:/etc/nginx/sites"
        environment:
            MONGODB_HOST: mongodb
        depends_on:
          - mongodb
