FROM vetal2409/nginx-php:latest

COPY docker/images.app/prod/scripts/after/20_fixtures.sh /var/scripts/after/

COPY . /var/www/norse
WORKDIR /var/www/norse

RUN mkdir -p web/runtime && chown -R 33:33 web/runtime
RUN composer install -n -o

RUN echo "* * * * * php -v >> /var/log/cron/default.log 2>&1" >> /etc/cron.d/default
